url: https://benasher.co
title: Ben Asher

plugins:
  - jekyll-sitemap

sass:
  style: compressed

description: "Ben Asher's personal website."
permalink: /:title/

exclude:
  - Makefile
  - vendor
  - Gemfile
  - Gemfile.lock
