url: https://benasher.co
title: Ben Asher
author: Ben Asher
description: Ben Asher's personal website and blog

plugins:
  - jekyll-sitemap
  - jekyll-feed

sass:
  style: compressed

description: "Ben Asher's personal website."
permalink: /:title/

exclude:
  - Makefile
  - vendor
  - Gemfile
  - Gemfile.lock
